#include <sys/ioctl.h>
#include <stdint.h>
#include <fcntl.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/mman.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>

#define XHLS_ACCEL_MAP_SIZE 0x40000


// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00000 : Control signals
//           bit 0  - ap_start (Read/Write/COH)
//           bit 1  - ap_done (Read/COR)
//           bit 2  - ap_idle (Read)
//           bit 3  - ap_ready (Read)
//           bit 7  - auto_restart (Read/Write)
//           others - reserved
// 0x00004 : Global Interrupt Enable Register
//           bit 0  - Global Interrupt Enable (Read/Write)
//           others - reserved
// 0x00008 : IP Interrupt Enable Register (Read/Write)
//           bit 0  - Channel 0 (ap_done)
//           bit 1  - Channel 1 (ap_ready)
//           others - reserved
// 0x0000c : IP Interrupt Status Register (Read/TOW)
//           bit 0  - Channel 0 (ap_done)
//           bit 1  - Channel 1 (ap_ready)
//           others - reserved
// 0x28000 : Data signal of N_Size
//           bit 31~0 - N_Size[31:0] (Read/Write)
// 0x28004 : reserved
// 0x28008 : Data signal of Mux_Factor
//           bit 31~0 - Mux_Factor[31:0] (Read/Write)
// 0x2800c : reserved
// 0x02000 ~
// 0x03fff : Memory 'local_state0_dend_V_dend' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_dend_V_dend[n]
// 0x04000 ~
// 0x05fff : Memory 'local_state0_dend_Hcurrent_q' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_dend_Hcurrent_q[n]
// 0x06000 ~
// 0x07fff : Memory 'local_state0_dend_Calcium_r' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_dend_Calcium_r[n]
// 0x08000 ~
// 0x09fff : Memory 'local_state0_dend_Potassium_s' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_dend_Potassium_s[n]
// 0x0a000 ~
// 0x0bfff : Memory 'local_state0_dend_I_CaH' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_dend_I_CaH[n]
// 0x0c000 ~
// 0x0dfff : Memory 'local_state0_dend_Ca2Plus' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_dend_Ca2Plus[n]
// 0x0e000 ~
// 0x0ffff : Memory 'local_state0_soma_g_CaL' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_soma_g_CaL[n]
// 0x10000 ~
// 0x11fff : Memory 'local_state0_soma_V_soma' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_soma_V_soma[n]
// 0x12000 ~
// 0x13fff : Memory 'local_state0_soma_Sodium_m' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_soma_Sodium_m[n]
// 0x14000 ~
// 0x15fff : Memory 'local_state0_soma_Sodium_h' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_soma_Sodium_h[n]
// 0x16000 ~
// 0x17fff : Memory 'local_state0_soma_Calcium_k' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_soma_Calcium_k[n]
// 0x18000 ~
// 0x19fff : Memory 'local_state0_soma_Calcium_l' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_soma_Calcium_l[n]
// 0x1a000 ~
// 0x1bfff : Memory 'local_state0_soma_Potassium_n' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_soma_Potassium_n[n]
// 0x1c000 ~
// 0x1dfff : Memory 'local_state0_soma_Potassium_p' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_soma_Potassium_p[n]
// 0x1e000 ~
// 0x1ffff : Memory 'local_state0_soma_Potassium_x_s' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_soma_Potassium_x_s[n]
// 0x20000 ~
// 0x21fff : Memory 'local_state0_axon_V_axon' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_axon_V_axon[n]
// 0x22000 ~
// 0x23fff : Memory 'local_state0_axon_Sodium_m_a' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_axon_Sodium_m_a[n]
// 0x24000 ~
// 0x25fff : Memory 'local_state0_axon_Sodium_h_a' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_axon_Sodium_h_a[n]
// 0x26000 ~
// 0x27fff : Memory 'local_state0_axon_Potassium_x_a' (2000 * 32b)
//           Word n : bit [31:0] - local_state0_axon_Potassium_x_a[n]
// 0x30000 ~
// 0x37fff : Memory 'Connectivity_Matrix' (8000 * 32b)
//           Word n : bit [31:0] - Connectivity_Matrix[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XHLS_ACCEL_AXILITES_ADDR_AP_CTRL                              0x00000
#define XHLS_ACCEL_AXILITES_ADDR_GIE                                  0x00004
#define XHLS_ACCEL_AXILITES_ADDR_IER                                  0x00008
#define XHLS_ACCEL_AXILITES_ADDR_ISR                                  0x0000c
#define XHLS_ACCEL_AXILITES_ADDR_N_SIZE_DATA                          0x28000
#define XHLS_ACCEL_AXILITES_BITS_N_SIZE_DATA                          32
#define XHLS_ACCEL_AXILITES_ADDR_MUX_FACTOR_DATA                      0x28008
#define XHLS_ACCEL_AXILITES_BITS_MUX_FACTOR_DATA                      32
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_DEND_V_DEND_BASE        0x02000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_DEND_V_DEND_HIGH        0x03fff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_DEND_V_DEND            32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_DEND_V_DEND            2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_DEND_HCURRENT_Q_BASE    0x04000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_DEND_HCURRENT_Q_HIGH    0x05fff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_DEND_HCURRENT_Q        32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_DEND_HCURRENT_Q        2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_DEND_CALCIUM_R_BASE     0x06000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_DEND_CALCIUM_R_HIGH     0x07fff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_DEND_CALCIUM_R         32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_DEND_CALCIUM_R         2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_DEND_POTASSIUM_S_BASE   0x08000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_DEND_POTASSIUM_S_HIGH   0x09fff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_DEND_POTASSIUM_S       32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_DEND_POTASSIUM_S       2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_DEND_I_CAH_BASE         0x0a000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_DEND_I_CAH_HIGH         0x0bfff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_DEND_I_CAH             32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_DEND_I_CAH             2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_DEND_CA2PLUS_BASE       0x0c000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_DEND_CA2PLUS_HIGH       0x0dfff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_DEND_CA2PLUS           32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_DEND_CA2PLUS           2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_G_CAL_BASE         0x0e000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_G_CAL_HIGH         0x0ffff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_SOMA_G_CAL             32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_SOMA_G_CAL             2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_V_SOMA_BASE        0x10000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_V_SOMA_HIGH        0x11fff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_SOMA_V_SOMA            32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_SOMA_V_SOMA            2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_SODIUM_M_BASE      0x12000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_SODIUM_M_HIGH      0x13fff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_SOMA_SODIUM_M          32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_SOMA_SODIUM_M          2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_SODIUM_H_BASE      0x14000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_SODIUM_H_HIGH      0x15fff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_SOMA_SODIUM_H          32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_SOMA_SODIUM_H          2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_CALCIUM_K_BASE     0x16000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_CALCIUM_K_HIGH     0x17fff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_SOMA_CALCIUM_K         32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_SOMA_CALCIUM_K         2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_CALCIUM_L_BASE     0x18000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_CALCIUM_L_HIGH     0x19fff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_SOMA_CALCIUM_L         32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_SOMA_CALCIUM_L         2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_POTASSIUM_N_BASE   0x1a000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_POTASSIUM_N_HIGH   0x1bfff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_SOMA_POTASSIUM_N       32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_SOMA_POTASSIUM_N       2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_POTASSIUM_P_BASE   0x1c000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_POTASSIUM_P_HIGH   0x1dfff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_SOMA_POTASSIUM_P       32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_SOMA_POTASSIUM_P       2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_POTASSIUM_X_S_BASE 0x1e000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_SOMA_POTASSIUM_X_S_HIGH 0x1ffff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_SOMA_POTASSIUM_X_S     32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_SOMA_POTASSIUM_X_S     2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_AXON_V_AXON_BASE        0x20000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_AXON_V_AXON_HIGH        0x21fff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_AXON_V_AXON            32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_AXON_V_AXON            2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_AXON_SODIUM_M_A_BASE    0x22000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_AXON_SODIUM_M_A_HIGH    0x23fff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_AXON_SODIUM_M_A        32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_AXON_SODIUM_M_A        2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_AXON_SODIUM_H_A_BASE    0x24000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_AXON_SODIUM_H_A_HIGH    0x25fff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_AXON_SODIUM_H_A        32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_AXON_SODIUM_H_A        2000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_AXON_POTASSIUM_X_A_BASE 0x26000
#define XHLS_ACCEL_AXILITES_ADDR_LOCAL_STATE0_AXON_POTASSIUM_X_A_HIGH 0x27fff
#define XHLS_ACCEL_AXILITES_WIDTH_LOCAL_STATE0_AXON_POTASSIUM_X_A     32
#define XHLS_ACCEL_AXILITES_DEPTH_LOCAL_STATE0_AXON_POTASSIUM_X_A     2000
#define XHLS_ACCEL_AXILITES_ADDR_CONNECTIVITY_MATRIX_BASE             0x30000
#define XHLS_ACCEL_AXILITES_ADDR_CONNECTIVITY_MATRIX_HIGH             0x37fff
#define XHLS_ACCEL_AXILITES_WIDTH_CONNECTIVITY_MATRIX                 32
#define XHLS_ACCEL_AXILITES_DEPTH_CONNECTIVITY_MATRIX                 8000

#define ALIGN_ADDR(x) x/4
// #define ALIGN_ADDR(x) x
#define HW_REGISTER(base,off) base[ALIGN_ADDR(off)]
//#define REG_WR(buff,base,off) *(int *)&base[ALIGN_ADDR(off)]=*(int *)&buff
#define REG_WR(buff,base,off) memcpy(&base[ALIGN_ADDR(off)],&buff,sizeof(float))
#define REG_RD(buff,base,off) *(int *)&buff=*(int *)&base[ALIGN_ADDR(off)]



#define CONDUCTANCE 0.04
#define NUM_STATE_VAR 19
// #define DEBUG

#define MAJOR_NUMBER 'k'
#define IOCTL_SET_DMA_SIZE_IN	_IOR(MAJOR_NUMBER, 0, int)
#define IOCTL_SET_DMA_SIZE_OUT	_IOR(MAJOR_NUMBER, 1, int)
#define IOCTL_SET_STEP	_IOR(MAJOR_NUMBER, 2, char *)
#define IOCTL_PROCESS_STEP	_IOR(MAJOR_NUMBER, 3, int)

struct Dev {
	int fd;
	char uiod[20];
	void *ptr;
} dev;

int start_hw(void *);

int set_network(void*, int, int, uint32_t *);

int write_step(int, void *, int, int, char *);

int read_step(int, int, char *);
